<a href="https://colab.research.google.com/github/omkarwazulkar/GoogleColab/blob/main/PyTorchTutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

a = torch.tensor(5)

In [3]:
a.shape

torch.Size([])

In [4]:
v = torch.tensor([1, 2, 3])
print(v, v.shape)

tensor([1, 2, 3]) torch.Size([3])


In [5]:
m = torch.tensor([[1, 2], [3, 4]])
print(m, m.shape)

tensor([[1, 2],
        [3, 4]]) torch.Size([2, 2])


In [10]:
x = torch.randn(3, 4, 4)
print(x, x.shape, x.ndim)

tensor([[[-8.1703e-01,  8.2966e-01, -1.1136e-01, -3.5123e-01],
         [-1.2779e+00, -1.3567e+00,  1.1940e+00,  8.6484e-01],
         [ 3.7571e-01,  8.5972e-01, -1.7732e+00,  3.7101e-01],
         [ 3.9591e-01,  1.1289e+00,  1.5072e-01, -7.0636e-01]],

        [[ 2.4834e-01, -1.0983e+00, -1.6116e-02, -9.6347e-01],
         [-7.0591e-01, -1.0755e+00,  1.5891e+00, -1.3260e+00],
         [-3.8100e-03,  7.6824e-01, -2.7192e-01,  1.0462e+00],
         [-4.3814e-01, -5.7107e-01,  1.3209e+00, -3.2290e-01]],

        [[-1.0057e+00,  3.2536e-01, -4.9781e-04,  3.2207e-01],
         [ 2.1658e-01, -5.9243e-02,  5.9520e-01, -9.4076e-01],
         [-2.7065e-01,  1.9253e-01, -4.5991e-01, -7.9834e-02],
         [-5.6986e-02,  1.0907e+00,  7.9335e-01, -8.9075e-01]]]) torch.Size([3, 4, 4]) 3


In [12]:
x = torch.randn(1000, 1000)  # huge tensor on GPU
y = x @ x.T  # fast matrix multiplication

In [15]:
y.ndim

2

In [4]:
import time
import torch

size = 5000
a_cpu = torch.randn(size, size)
b_cpu = torch.randn(size, size)

# CPU
start = time.time()
c_cpu = a_cpu @ b_cpu
print("CPU time:", time.time() - start)

# GPU
device = "cuda"
a_gpu = a_cpu.to(device)
b_gpu = b_cpu.to(device)

torch.cuda.synchronize()  # make sure GPU is ready
start = time.time()
c_gpu = a_gpu @ b_gpu
torch.cuda.synchronize()
print("GPU time:", time.time() - start)

CPU time: 1.7904143333435059
GPU time: 0.08813047409057617


In [5]:
A = torch.randn(2, 3)
B = torch.randn(2, 3)

# Elementwise
print(A + B)
print(A * B)

# Matrix multiplication
C = torch.randn(3, 4)
print(A @ C)  # (2x3) @ (3x4) = (2x4)

tensor([[-0.3537,  2.5938,  2.1157],
        [ 0.2219,  1.1716, -3.6131]])
tensor([[-0.2360,  1.6361,  1.0118],
        [-0.6428,  0.2846,  2.5856]])
tensor([[ 4.4105, -0.2773,  2.9324, -0.1122],
        [-0.4561,  1.8802, -1.7911,  2.1364]])


In [6]:
x = torch.tensor([[10, 20, 30],
                  [40, 50, 60]])

print(x[0, :])     # First row
print(x[:, 1])     # Second column
print(x[1, 2])     # Single element

tensor([10, 20, 30])
tensor([20, 50])
tensor(60)


In [7]:
x[0, 0] = 999
print(x)

tensor([[999,  20,  30],
        [ 40,  50,  60]])


In [8]:
import torch

x = torch.tensor([1, 2, 3])
x[0] = 99
print(x)

tensor([99,  2,  3])


In [9]:
y = x[1:3]
y[0] = 77       # modifies original x as well
print(x)        # tensor([99, 77, 3])

tensor([99, 77,  3])


In [11]:
y = x[1:3].clone()
y[0] = 100
print(x)  # x stays the same

tensor([99, 77,  3])


In [12]:
x = torch.randn(2, 3)
y = x.reshape(3, 2)
print(y)

z = x.view(-1)   # flatten
print(z)

tensor([[ 0.5478, -0.2346],
        [-0.1077, -0.0104],
        [-0.7697, -1.9080]])
tensor([ 0.5478, -0.2346, -0.1077, -0.0104, -0.7697, -1.9080])


In [16]:
x = torch.randn(3, 4)
b = torch.randn(4)

print(x,"\n",b,"\n")
print(x + b)

tensor([[-0.0112, -0.6094,  0.5874,  0.0241],
        [-0.2125, -1.2655,  0.8899, -0.1406],
        [ 0.5858,  0.8520, -1.6076,  1.7763]]) 
 tensor([ 0.6948, -0.2616,  0.4202, -1.1597]) 

tensor([[ 0.6836, -0.8710,  1.0076, -1.1357],
        [ 0.4823, -1.5270,  1.3101, -1.3003],
        [ 1.2806,  0.5904, -1.1874,  0.6165]])


In [20]:
def inspect(t):
  return t, t.shape, t.ndim, t.dtype

In [33]:
t = torch.randn(2, 3, 4)

In [34]:
inspect(t)

(tensor([[[ 0.6359,  0.9944, -0.4318, -0.0440],
          [ 1.4372, -1.5088, -0.8281,  0.1388],
          [-2.3345, -0.8758,  0.9894,  1.1004]],
 
         [[-0.8767,  0.9444,  0.9972, -1.1039],
          [-0.5098, -0.4458,  0.7454, -0.0252],
          [ 0.9091, -0.2611, -0.5377,  1.9186]]]),
 torch.Size([2, 3, 4]),
 3,
 torch.float32)

In [35]:
# Step 1: Create tensor with requires_grad
x = torch.tensor(4.0, requires_grad=True)

# Step 2: Define a function of x
z = 2*x**2 + 3*x + 1

# Step 3: Backward pass
z.backward()  # computes dz/dx

# Step 4: Check gradient
print(x.grad)  # should be 19

tensor(19.)


In [118]:
x_train = torch.tensor([2.0, 3.0, 4.0, 5.0])

In [16]:
x_train = torch.tensor([2.0, 3.0, 4.0, 5.0]).view(-1, 1)  # Column Vector

In [119]:
x_train, x_train.shape, x_train.ndim

(tensor([2., 3., 4., 5.]), torch.Size([4]), 1)

In [14]:
W = torch.randn(1, requires_grad=True)

In [15]:
W, W.shape, W.ndim

(tensor([-0.1559], requires_grad=True), torch.Size([1]), 1)

In [105]:
import torch
import torch.nn as nn
import torch.optim as optim

x_train = torch.tensor([[[2.0, 6.0, 8.0],
                        [3.0, 9.0, 12.0],
                        [4.0, 12.0, 16.0],
                        [5.0, 15.0, 20.0]],

                       [[2.0, 6.0, 8.0],
                        [3.0, 9.0, 12.0],
                        [4.0, 12.0, 16.0],
                        [5.0, 15.0, 20.0]]])

y_train = torch.tensor([[4.0],
                        [6.0]])

In [106]:
x_train.shape, y_train.shape

(torch.Size([2, 4, 3]), torch.Size([2, 1]))

In [107]:
x_train_flat = x_train.view(2, -1)

In [115]:
x_train_flat = x_train_flat / 20.0  # simple normalization
y_train_scaled = y_train / 6.0

In [116]:
x_train_flat

tensor([[0.0050, 0.0150, 0.0200, 0.0075, 0.0225, 0.0300, 0.0100, 0.0300, 0.0400,
         0.0125, 0.0375, 0.0500],
        [0.0050, 0.0150, 0.0200, 0.0075, 0.0225, 0.0300, 0.0100, 0.0300, 0.0400,
         0.0125, 0.0375, 0.0500]])

In [117]:
y_train_scaled

tensor([[0.6667],
        [1.0000]])

In [111]:
model = nn.Linear(in_features=x_train_flat.shape[1], out_features=1)
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.001)

In [112]:
for step in range(1, 200):
  y_pred = model(x_train_flat)
  loss = criterion(y_pred, y_train_scaled)
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()
  w, b = model.parameters()
  print(f"W = {w}\nB = {b}")
  print(f"Step {step}: Loss = {loss.item():.4f}, Predictions = {y_pred.squeeze().tolist()}\n")

W = Parameter containing:
tensor([[-0.1718,  0.0618,  0.2244, -0.1274,  0.0699, -0.2613,  0.2109,  0.0181,
          0.2608,  0.2045, -0.2331,  0.1686]], requires_grad=True)
B = Parameter containing:
tensor([0.1530], requires_grad=True)
Step 1: Loss = 0.0190, Predictions = [0.40539440512657166, 0.40539440512657166]

W = Parameter containing:
tensor([[-0.1718,  0.0618,  0.2245, -0.1274,  0.0700, -0.2612,  0.2109,  0.0182,
          0.2609,  0.2045, -0.2330,  0.1688]], requires_grad=True)
B = Parameter containing:
tensor([0.1532], requires_grad=True)
Step 2: Loss = 0.0188, Predictions = [0.40624770522117615, 0.40624770522117615]

W = Parameter containing:
tensor([[-0.1718,  0.0619,  0.2246, -0.1273,  0.0701, -0.2611,  0.2110,  0.0183,
          0.2611,  0.2046, -0.2328,  0.1689]], requires_grad=True)
B = Parameter containing:
tensor([0.1534], requires_grad=True)
Step 3: Loss = 0.0186, Predictions = [0.407093346118927, 0.407093346118927]

W = Parameter containing:
tensor([[-0.1718,  0.062

In [120]:
import torch
import torch.nn as nn
import torch.optim as optim

# Example data: 2 “images”, each 4x3
x_train = torch.tensor([[[2.0, 6.0, 8.0],
                         [3.0, 9.0, 12.0],
                         [4.0, 12.0, 16.0],
                         [5.0, 15.0, 20.0]],

                        [[2.0, 6.0, 8.0],
                         [3.0, 9.0, 12.0],
                         [4.0, 12.0, 16.0],
                         [5.0, 15.0, 20.0]]], dtype=torch.float32)

y_train = torch.tensor([[4.0], [6.0]], dtype=torch.float32)

# Flatten input: each image → 12 features
x_train_flat = x_train.view(2, -1) / 20.0  # normalize

# Design neural network using Sequential
model = nn.Sequential(
    nn.Linear(12, 8),
    nn.ReLU(),
    nn.Linear(8, 4),
    nn.ReLU(),
    nn.Linear(4, 1)
)

# Loss and optimizer
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

# Training loop
for step in range(20):
    y_pred = model(x_train_flat)
    loss = criterion(y_pred, y_train / 10.0)  # normalize target
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    print(f"Step {step+1}: Loss = {loss.item():.6f}")

Step 1: Loss = 0.117391
Step 2: Loss = 0.112887
Step 3: Loss = 0.108571
Step 4: Loss = 0.104437
Step 5: Loss = 0.100476
Step 6: Loss = 0.096680
Step 7: Loss = 0.093044
Step 8: Loss = 0.089560
Step 9: Loss = 0.086222
Step 10: Loss = 0.083024
Step 11: Loss = 0.079959
Step 12: Loss = 0.077023
Step 13: Loss = 0.074210
Step 14: Loss = 0.071514
Step 15: Loss = 0.068931
Step 16: Loss = 0.066456
Step 17: Loss = 0.064085
Step 18: Loss = 0.061812
Step 19: Loss = 0.059635
Step 20: Loss = 0.057549


# **Boston Housing Dataset**

In [4]:
import pandas as pd

In [5]:
data = "/content/BostonHousing.csv"

In [7]:
df = pd.read_csv(data)
print(df.head())

      crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2  


In [8]:
df.columns = df.columns.str.upper()

In [9]:
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        B  LSTAT  MEDV  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [10]:
df.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT        MEDV  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    int64  
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64  
 9   TAX      506 non-null    int64  
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 55.5 KB


In [12]:
corr = df.corr()

In [13]:
corr["MEDV"].sort_values(ascending=True)

LSTAT     -0.737663
PTRATIO   -0.507787
INDUS     -0.483725
TAX       -0.468536
NOX       -0.427321
CRIM      -0.388305
RAD       -0.381626
AGE       -0.376955
CHAS       0.175260
DIS        0.249929
B          0.333461
ZN         0.360445
RM         0.695360
MEDV       1.000000
Name: MEDV, dtype: float64

In [14]:
df.isnull().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
MEDV       0
dtype: int64

In [15]:
X = df.drop("MEDV", axis=1)

In [16]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

In [17]:
features_scaled = scaler.fit_transform(X)

In [18]:
X_scaled = pd.DataFrame(features_scaled, columns=X.columns)

In [19]:
X_scaled

CRIM        ZN     INDUS      CHAS       NOX        RM       AGE  \
0   -0.419782  0.284830 -1.287909 -0.272599 -0.144217  0.413672 -0.120013   
1   -0.417339 -0.487722 -0.593381 -0.272599 -0.740262  0.194274  0.367166   
2   -0.417342 -0.487722 -0.593381 -0.272599 -0.740262  1.282714 -0.265812   
3   -0.416750 -0.487722 -1.306878 -0.272599 -0.835284  1.016303 -0.809889   
4   -0.412482 -0.487722 -1.306878 -0.272599 -0.835284  1.228577 -0.511180   
..        ...       ...       ...       ...       ...       ...       ...   
501 -0.413229 -0.487722  0.115738 -0.272599  0.158124  0.439316  0.018673   
502 -0.415249 -0.487722  0.115738 -0.272599  0.158124 -0.234548  0.288933   
503 -0.413447 -0.487722  0.115738 -0.272599  0.158124  0.984960  0.797449   
504 -0.407764 -0.487722  0.115738 -0.272599  0.158124  0.725672  0.736996   
505 -0.415000 -0.487722  0.115738 -0.272599  0.158124 -0.362767  0.434732   

          DIS       RAD       TAX   PTRATIO         B     LSTAT  
0    0.140214 -0.982843 -0.666608 -1.459000  0.441052 -1.075562  
1    0.557160 -0.867883 -0.987329 -0.303094  0.441052 -0.492439  
2    0.557160 -0.867883 -0.987329 -0.303094  0.396427 -1.208727  
3    1.077737 -0.752922 -1.106115  0.113032  0.416163 -1.361517  
4    1.077737 -0.752922 -1.106115  0.113032  0.441052 -1.026501  
..        ...       ...       ...       ...       ...       ...  
501 -0.625796 -0.982843 -0.803212  1.176466  0.387217 -0.418147  
502 -0.716639 -0.982843 -0.803212  1.176466  0.441052 -0.500850  
503 -0.773684 -0.982843 -0.803212  1.176466  0.441052 -0.983048  
504 -0.668437 -0.982843 -0.803212  1.176466  0.403225 -0.865302  
505 -0.613246 -0.982843 -0.803212  1.176466  0.441052 -0.669058  

[506 rows x 13 columns]

In [20]:
X_scaled.iloc[:, 0].mean()

np.float64(-1.1233877245218975e-16)

In [21]:
X_scaled.iloc[:, 0].std()

1.0009896093465713

In [22]:
y = df["MEDV"]

In [23]:
import torch

X_t = torch.tensor(X_scaled.values, dtype=torch.float32)
y_t = torch.tensor(y.values, dtype=torch.float32).view(-1, 1)

In [24]:
X_t.shape, y_t.shape

(torch.Size([506, 13]), torch.Size([506, 1]))

In [25]:
X_t[0]

tensor([-0.4198,  0.2848, -1.2879, -0.2726, -0.1442,  0.4137, -0.1200,  0.1402,
        -0.9828, -0.6666, -1.4590,  0.4411, -1.0756])

In [26]:
y_t[0]

tensor([24.])

In [27]:
import torch.nn as nn

class BostonNN(nn.Module):
  def __init__(self):
    super(BostonNN, self).__init__()
    self.model = nn.Sequential(
        nn.Linear(13, 32),
        nn.ReLU(),
        nn.Linear(32, 1)
    )

  def forward(self, x):
    return self.model(x)

In [28]:
net = BostonNN()

In [29]:
net

BostonNN(
  (model): Sequential(
    (0): Linear(in_features=13, out_features=32, bias=True)
    (1): ReLU()
    (2): Linear(in_features=32, out_features=1, bias=True)
  )
)

In [38]:
import torch.optim as optim

criterion = nn.MSELoss()
optimizer = optim.Adam(net.parameters(), lr=0.1)

In [40]:
num_epochs = 1000

for epoch in range(num_epochs):
  net.train()

  y_pred = net(X_t)
  loss = criterion(y_pred, y_t)
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

  if epoch%20==0:
    print(f"Epoch {epoch}, Loss: {loss.item():.4f}")

Epoch 0, Loss: 4.0291
Epoch 20, Loss: 3.8753
Epoch 40, Loss: 3.7360
Epoch 60, Loss: 3.6246
Epoch 80, Loss: 3.5368
Epoch 100, Loss: 3.4721
Epoch 120, Loss: 3.4216
Epoch 140, Loss: 3.3876
Epoch 160, Loss: 3.3571
Epoch 180, Loss: 3.3048
Epoch 200, Loss: 3.2630
Epoch 220, Loss: 3.2345
Epoch 240, Loss: 3.2233
Epoch 260, Loss: 3.1512
Epoch 280, Loss: 3.1594
Epoch 300, Loss: 3.0631
Epoch 320, Loss: 3.0835
Epoch 340, Loss: 2.9902
Epoch 360, Loss: 2.9707
Epoch 380, Loss: 2.8996
Epoch 400, Loss: 2.9676
Epoch 420, Loss: 3.1695
Epoch 440, Loss: 3.0611
Epoch 460, Loss: 2.7901
Epoch 480, Loss: 3.5014
Epoch 500, Loss: 2.8096
Epoch 520, Loss: 2.7148
Epoch 540, Loss: 2.8060
Epoch 560, Loss: 2.6986
Epoch 580, Loss: 3.0811
Epoch 600, Loss: 3.4002
Epoch 620, Loss: 2.5826
Epoch 640, Loss: 2.5784
Epoch 660, Loss: 2.7037
Epoch 680, Loss: 2.6230
Epoch 700, Loss: 2.5685
Epoch 720, Loss: 2.6058
Epoch 740, Loss: 2.5595
Epoch 760, Loss: 2.4832
Epoch 780, Loss: 2.5792
Epoch 800, Loss: 2.7297
Epoch 820, Loss: 2.591

In [41]:
net.eval()
with torch.no_grad():
    val_pred = net(X_t)
    print("Sample predictions:", val_pred[:5].squeeze())

Sample predictions: tensor([23.3523, 23.1164, 32.8369, 32.7099, 34.5160])
